@base = http://localhost:8888/.netlify/functions

### Testing
get {{base}}/hello

###

post {{base}}/code
Content-Type: application/json

{
  "code": "E1mgLy8rKm11Phrk9CHXhWFTUGQBjx"
}

###

get {{base}}/me
Authorization: Bearer LVF4ZfTD51yXPm27XzZ09AO1a2hdKz

### Get public profiles

get {{base}}/profiles